mh_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0005
  kinematics_solver_timeout: 1
  kinematics_solver_attempts: 3
mh_eef:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0005
  kinematics_solver_timeout: 1
  kinematics_solver_attempts: 3