robotis_manipulator_h:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  mh_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6